---
name: {{ NAME }}
env: {{ ENV }}

bind_addr: {{ HOST }}
http_port: {{ PORT }}
redis_dsn: redis://{{REDIS_HOST}}:{{REDIS_PORT or '6379'}}
images_path: {{IMAGES_PATH}}
images:
  base:
    path: {{ BASE_IMG_PATH is defined and BASE_IMG_PATH or (IMAGES_PATH+'/band_base') }}
    name: rst/band-base
  collection:
    path: {{IMAGES_PATH}}/band_collection
    name: rst/band-service-base
network: custom

container_env:
  'BAND_URL': http://band:{{PORT}}
  'REDIS_HOST': {{REDIS_HOST}}
  'REDIS_DSN': redis://{{REDIS_HOST}}:{{REDIS_PORT or '6379'}}/{{REDIS_DB or 2}}
