---
name: {{NAME}}
env: {{ENV}}

listen: "{{HOST|default('0.0.0.0')}}:{{PORT}}"
redis_dsn: "redis://{{REDIS_HOST}}:{{REDIS_PORT|default(6379)}}"
images_path: {{IMAGES_PATH}}
images:
  base:
    path: "{{BASE_IMG_PATH|default(IMAGES_PATH+'/band_base')}}"
    name: rst/band-base
  collection:
    path: "{{IMAGES_PATH}}/band_collection"
    name: rst/band-service-base
container_params:
  network: custom
  memory: 367001600 # limit 350mb
  bind_ip: "{{BIND_HOST_IP}}"

container_env:
  HOST: '0.0.0.0'
  BAND_URL: "{{BAND_URL|default('http://{{BIND_HOST_IP}}:{{PORT}}')}}"
  REDIS_HOST: "{{CONT_REDIS_HOST}}"
  REDIS_DSN: "redis://{{CONT_REDIS_HOST}}:{{REDIS_PORT|default(6379)}}"
