---
name: {{ NAME }}
env: {{ ENV }}

bind_addr: {{ HOST }}
http_port: {{ PORT }}
redis_dsn: redis://{{REDIS_HOST}}:{{REDIS_PORT or '6379'}}
images_path: {{IMAGES_PATH}}
base_image_path: {{IMAGES_PATH}}/band_base
base_image_name: rst/band-base
def_srv_img_path: {{IMAGES_PATH}}/band_collection
def_srv_img_name: rst/band-service-base
network: custom

container_env:
  'BAND_URL': http://band:{{PORT}}
  'REDIS_HOST': {{REDIS_HOST}}
  'REDIS_DSN': redis://{{REDIS_HOST}}:{{REDIS_PORT or '6379'}}/{{REDIS_DB or 2}}
